Seo
rheviu/hello pull request #5
Opened 2021-02-21 00:28 UTC by DiegoEmilio01

Basic SEO done. Performance would improve with lower resolution images.
Check console logs, head links cause some and are unkown by me.

2021-02-21 22:07 UTC, nbcl requested changes
Hey @DiegoEmilio01!

Everything looks good.

I have added two comments about minor fixes that should be considered before merging.

Apart from that, regarding the following reports:

> Performance would improve with lower resolution images.
Check console logs, head links cause some and are unknown by me.

In benefit of the current workflow, please avoid leaving open-ended remarks in pull requests, as this are valid observations that are to be considered by the team and should be reported as individual issues.

2021-02-21 22:07 UTC, nbcl commented on index.html
> +    <link media="screen" rel="preload" as="font" href="https://rsms.me/inter/inter.css" />
This external resource link loads the desired `.woff` files, but it is still a stylesheet itself, so we should load it as follows.

```html
<link media="screen" rel="stylesheet preload" as="style" href="https://rsms.me/inter/inter.css" />
```

2021-02-21 22:07 UTC, nbcl commented on index.html
>      <meta name="author" content="">
Line `9` contain the same metadata element assigned in line `6`, overriding the description.

2021-02-24 18:15 UTC, DiegoEmilio01 commented
@nbcl resolved all comments, the pull request should be ready for merge!

2021-02-26 00:22 UTC, nbcl approved these changes

2021-02-26 00:23 UTC, merged